# Generated by Django 3.2.14 on 2022-07-25 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('depts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_dept', related_query_name='core_depts', to='core.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
